csg_call: added a lot of useful option, see --help

diff --git a/scripts/csg_call b/scripts/csg_call
--- a/scripts/csg_call
+++ b/scripts/csg_call
@@ -1,34 +1,83 @@
 #!/bin/bash
 
+sw_opt=""
+
 #we have to dedine this if $SOURCE_WRAPPER functions common fails
 die() {
   echo -e "$*" >&2
   exit 1
 }
 
-if [ "$1" = "--help" ]; then
-  echo This script calls script for csg using source_wrapper
-  echo Usage: ${0##*/} key1 key2
-  echo Example: ${0##*/} table smooth [ARGUMENTS]
-  echo USES: \$CSGSHARE
-  echo NEEDS: 
-  exit 0
-fi
+show_help () {
+  cat << eof
+This script calls script for csg using source_wrapper
+Usage: ${0##*/} key1 key2
+OPTIONS:
+-l, --list          Show list of all script
+    --check         Check csg script
+    --scriptdir DIR Set the user script dir
+-h, --help          Show this help
+
+Example: ${0##*/} table smooth [ARGUMENTS]
+
+USES: \$CSGSHARE
+NEEDS:
+eof
+}
 
 
-[[ -z "$2" ]] && die "${0##*/}: Missing argument"
+while [ "${1#-}" != "$1" ]; do
+ if [ "${1#--}" = "$1" ] && [ -n "${1:2}" ]; then
+    #short opt with arguments here: fc
+    if [ "${1#-[fc]}" != "${1}" ]; then
+       set -- "${1:0:2}" "${1:2}" "${@:2}"
+    else
+       set -- "${1:0:2}" "-${1:2}" "${@:2}"
+    fi
+ fi
+ case $1 in
+   -l | --list)
+    #we can not run it directly here SOURCE_WRAPPER is defined later
+    sw_opt="--status"
+    shift ;;
+   --check)
+    #we can not run it directly here SOURCE_WRAPPER is defined later
+    sw_opt="--check"
+    shift ;;
+   --scriptdir)
+    export CSGSCRIPTDIR="$2"
+    shift 2;; 
+   -h | --help)
+    show_help
+    exit 0;;
+  *)
+   die "Unknown option '$1'";;
+ esac
+done
 
-[[ -n "${CSGSHARE}" ]] || die "${0##*/}: Environment values CSGSHARE not defined"
+[ -z "$2" ] && [ -z "$sw_opt" ] && die "${0##*/}: Missing argument"
+
+[ -n "${CSGSHARE}" ] || die "${0##*/}: Environment values CSGSHARE not defined"
 
 echo \$CSGSHARE is ${CSGSHARE}
 
 export CSGINVERSE=$CSGSHARE/scripts/inverse
-[[ -d "$CSGINVERSE" ]] || die "${0##*/}: CSGINVERSE '$CSGINVERSE' is not a dir"
+[ -d "$CSGINVERSE" ] || die "${0##*/}: CSGINVERSE '$CSGINVERSE' is not a dir"
 
 export SOURCE_WRAPPER=$CSGINVERSE/source_wrapper.pl
-[[ -x "$SOURCE_WRAPPER" ]] || die "${0##*/}: Could not execute source wrapper"
+[ -x "$SOURCE_WRAPPER" ] || die "${0##*/}: Could not execute source wrapper"
 
-source $($SOURCE_WRAPPER functions common) || die "$SOURCE_WRAPPER functions common failed" 
+source $($SOURCE_WRAPPER functions common) || die "$SOURCE_WRAPPER functions common failed"
+
+if [ -n "${CSGSCRIPTDIR}" ]; then 
+  [ -d "$CSGSCRIPTDIR" ] || die "${0##*/}: CSGSCRIPTDIR '$CSGSCRIPTDIR' is not a dir"
+  echo \$CSGSCRIPTDIR is ${CSGSCRIPTDIR}
+fi
+
+if [ -n "$sw_opt" ]; then
+  $SOURCE_WRAPPER $sw_opt
+  exit 0
+fi
 
 #script=$($SOURCE_WRAPPER $1 $2)
 #echo running $script
