pmf checking for completed steps

diff --git a/scripts/csg_pmf b/scripts/csg_pmf
--- a/scripts/csg_pmf
+++ b/scripts/csg_pmf
@@ -139,39 +139,44 @@ filelist="$(csg_get_property --allow-empty cg.inverse.filelist)"
 
 # Step 0 - Initialization
 update_stepnames 0
+
 this_dir=$(get_current_step_dir --no-check)
 pmf_step=$(basename $this_dir)
 
-conf_in=$(csg_get_property --allow-empty cg.non-bonded.conf_in)
-
-if [ -z "$conf_in" ]; then
-  
-  conf_init=$(csg_get_property cg.non-bonded.conf_init)
-  mdp_init=$(csg_get_property cg.non-bonded.mdp_init)
-  
-  msg "---------------"
-  msg "Doing $pmf_step"
-  msg "---------------"
-  mkdir -p $this_dir || die "mkdir -p $this_dir failed"
-  cd $this_dir || die "cd $this_dir failed"
-
-  cp_from_main_dir $filelist
-  critical cp_from_main_dir grompp.mdp.template ${mdp_init} ${conf_init} 
-
-  do_external initialize pmf
- 
-  index="$this_dir/index.ndx"
-  grompp="$this_dir/grompp.mdp"
-  touch "done"
-  msg "$pmf_step is done"
-  cd $main_dir
+if [ -f $this_dir/done ]; then
+  msg "step $pmf_step is already done - skipping"0
 else
-  mkdir step_000
-  msg "$pmf_step is already done"
-  conf_out=$(csg_get_property cg.non-bonded.conf_in)
-  critical cp $(conf_out) step_000/confout.gro
-  index=$(csg_get_property cg.non-bonded.index)
-  grompp="$main_dir/grompp.mdp"
+  conf_in=$(csg_get_property --allow-empty cg.non-bonded.conf_in)
+
+  if [ -z "$conf_in" ]; then
+  
+    conf_init=$(csg_get_property cg.non-bonded.conf_init)
+    mdp_init=$(csg_get_property cg.non-bonded.mdp_init)
+  
+    msg "---------------"
+    msg "Doing $pmf_step"
+    msg "---------------"
+    mkdir -p $this_dir || die "mkdir -p $this_dir failed"
+    cd $this_dir || die "cd $this_dir failed"
+
+    cp_from_main_dir $filelist
+    critical cp_from_main_dir grompp.mdp.template ${mdp_init} ${conf_init} 
+
+    do_external initialize pmf
+ 
+    index="$this_dir/index.ndx"
+    grompp="$this_dir/grompp.mdp"
+    touch "done"
+    echo "$pmf_step is done"
+    cd $main_dir
+  else
+    mkdir step_000
+    msg "$pmf_step is already done"
+    conf_out=$(csg_get_property cg.non-bonded.conf_in)
+    critical cp $(conf_out) step_000/confout.gro
+    index=$(csg_get_property cg.non-bonded.index)
+    grompp="$main_dir/grompp.mdp"
+  fi
 fi
 
 # Step 1 - Generate configurations
@@ -182,22 +187,27 @@ pmf_step=$(basename $this_dir)
 msg "---------------"
 msg "Doing $pmf_step"
 msg "---------------"
-mkdir -p $this_dir || die "mkdir -p $this_dir failed"
 
-cd $this_dir || die "cd $this_dir failed"
+if [ -f $this_dir/done ]; then
+  msg "step $pmf_step is already done - skipping"
+else
+  mkdir -p $this_dir || die "mkdir -p $this_dir failed"
 
-cp_from_main_dir $filelist
-critical cp_from_main_dir grompp.mdp.template 
-critical cp_from_last_step confout.gro 
-#critical cp_from_main_dir ${grompp} start_in.mdp
-critical cp_from_main_dir start_in.mdp
-critical mv confout.gro conf.gro
+  cd $this_dir || die "cd $this_dir failed"
 
-do_external prepare pmf
+  cp_from_main_dir $filelist
+  cp_from_main_dir grompp.mdp.template 
+  cp_from_last_step confout.gro 
+  #critical cp_from_main_dir ${grompp} start_in.mdp
+  cp_from_main_dir start_in.mdp
+  critical mv confout.gro conf.gro
 
-touch "done"
-msg "$pmf_step is done"
-cd $main_dir
+  do_external prepare pmf
+
+  touch "done"
+  echo "$pmf_step is done"
+  cd $main_dir
+fi
 
 # Step 3 - Run simulations
 update_stepnames 2
@@ -207,38 +217,47 @@ pmf_step=$(basename $this_dir)
 msg "---------------"
 msg "Doing $pmf_step"
 msg "---------------"
-mkdir -p $this_dir || die "mkdir -p $this_dir failed"
-cd $this_dir || die "cd $this_dir failed"
 
-critical cp $last_dir/topol.top .
-critical cp $last_dir/index.ndx .
-critical cp $last_dir/grompp.mdp.template .
-critical cp $last_dir/conf_start*.gro .
-critical cp $last_dir/*.itp .
-critical cp $last_dir/dist.xvg .
+if [ -f $this_dir/done ]; then
+  msg "step $pmf_step is already done - skipping"
+else
+  mkdir -p $this_dir || die "mkdir -p $this_dir failed"
+  cd $this_dir || die "cd $this_dir failed"
 
-do_external simulate pmf
+  cp_from_main_dir $filelist
+  cp_from_main_dir grompp.mdp.template
+  cp_from_last_step conf_start*.gro 
+  cp_from_last_step rdist.xvg
 
-touch "done"
-msg "$pmf_step is done"
-cd $main_dir
+  do_external simulate pmf
+
+  touch "done"
+  echo "$pmf_step is done"
+  cd $main_dir
+fi
 
 # Step 4 - Calculate pmf
 update_stepnames 3
 this_dir=$(get_current_step_dir --no-check)
+
 last_dir=$(get_last_step_dir)
 pmf_step=$(basename $this_dir)
 msg "---------------"
 msg "Doing $pmf_step"
 msg "---------------"
-mkdir -p $this_dir || die "mkdir -p $this_dir failed"
-cd $this_dir || die "cd $this_dir failed"
 
-do_external calc pmf
+if [ -f $this_dir/done ]; then
+  msg "step $pmf_step is already done - skipping"
+else
+  mkdir -p $this_dir || die "mkdir -p $this_dir failed"
+  cd $this_dir || die "cd $this_dir failed"
 
-touch "done"
-msg "$pmf_step is done"
-cd $main_dir
+  do_external calc pmf
+
+  touch "done"
+  echo "$pmf_step is done"
+  cd $main_dir
+fi
 
 # Step 5 - Calculate rdf
 update_stepnames 4
@@ -248,13 +267,18 @@ pmf_step=$(basename $this_dir)
 msg "---------------"
 msg "Doing $pmf_step"
 msg "---------------"
-mkdir -p $this_dir || die "mkdir -p $this_dir failed"
-cd $this_dir || die "cd $this_dir failed"
 
-critical cp $last_dir/grompp.mdp .
+if [ -f $this_dir/done ]; then
+  msg "step $pmf_step is already done - skipping"
+else
+  mkdir -p $this_dir || die "mkdir -p $this_dir failed"
+  cd $this_dir || die "cd $this_dir failed"
 
-do_external calc rdf
+  critical cp $last_dir/grompp.mdp .
 
-touch "done"
-msg "$pmf_step is done"
-cd $main_dir
+  do_external calc rdf
+
+  touch "done"
+  echo "$pmf_step is done"
+  cd $main_dir
+fi
