cleaned up pmf stuff

diff --git a/scripts/csg_pmf b/scripts/csg_pmf
--- a/scripts/csg_pmf
+++ b/scripts/csg_pmf
@@ -122,65 +122,58 @@ show_csg_tables
 
 mdrun="$(csg_get_property --allow-empty cg.inverse.gromacs.mdrun.bin "mdrun")"
 
-# if no -rerun option, run as normal
-if [[ $mdrun != *-rerun* ]]; then
+#----------------------------------------------------------------------------------------------------
+# Step 0 - Initialization
+update_stepnames 0
 
-  # Step 0 - Initialization
-  update_stepnames 0
+this_dir=$(get_current_step_dir --no-check)
+pmf_step=$(basename $this_dir)
 
-  this_dir=$(get_current_step_dir --no-check)
-  pmf_step=$(basename $this_dir)
-
-  if [ -f $this_dir/done ]; then
-    msg "step $pmf_step is already done - skipping"
-  else 
-    msg "---------------"
-    msg "Doing $pmf_step"
-    msg "---------------"
-    mkdir -p $this_dir || die "mkdir -p $this_dir failed"
-    cd $this_dir || die "cd $this_dir failed"
-
-    cp_from_main_dir $filelist
-    do_external initialize pmf
-    touch "done"
-    echo "$pmf_step is done"
-    cd $main_dir
-  fi
-
-  # Step 1 - Generate configurations
-  update_stepnames 1
-  this_dir=$(get_current_step_dir --no-check)
-  last_dir=$(get_last_step_dir)
-  pmf_step=$(basename $this_dir)
+if [ -f $this_dir/done ]; then
+  msg "step $pmf_step is already done - skipping"
+else 
   msg "---------------"
   msg "Doing $pmf_step"
   msg "---------------"
+  mkdir -p $this_dir || die "mkdir -p $this_dir failed"
+  cd $this_dir || die "cd $this_dir failed"
+  set +x
+  cp_from_main_dir $filelist
 
-  if [ -f $this_dir/done ]; then
-    msg "step $pmf_step is already done - skipping"
-  else
-    mkdir -p $this_dir || die "mkdir -p $this_dir failed"
+  do_external initialize pmf
 
-    cd $this_dir || die "cd $this_dir failed"
+  touch "done"
+  echo "$pmf_step is done"
+  cd $main_dir
+fi
 
-    cp_from_main_dir $filelist
-    cp_from_main_dir grompp.mdp.template 
+# Step 1 - Generate configurations
+update_stepnames 1
+this_dir=$(get_current_step_dir --no-check)
+last_dir=$(get_last_step_dir)
+pmf_step=$(basename $this_dir)
+msg "---------------"
+msg "Doing $pmf_step"
+msg "---------------"
+if [ -f $this_dir/done ]; then
+  msg "step $pmf_step is already done - skipping"
+else
+  mkdir -p $this_dir || die "mkdir -p $this_dir failed"
+  cd $this_dir || die "cd $this_dir failed"
+  cp_from_main_dir $filelist
+  if [ -f $last_dir/done ]; then
     cp_from_last_step confout.gro 
     critical mv confout.gro conf.gro
-
-    do_external prepare pmf
-
-    touch "done"
-    echo "$pmf_step is done"
-    cd $main_dir
+  else
+    cp_from_last_step conf.gro
   fi
 
-else
-  old_pmf="$(csg_get_property cg.non-bonded.pmf.old_pmf)"
-  [ -d "$old_pmf" ] || die "${0##*/}: old pmf dir '$old_pmf' not found"
-  msg "Preparing 'mdrun -rerun' from $old_pmf"
-  cp -r $old_pmf/step_001 .
-fi # end if no -rerun option
+  do_external prepare pmf
+
+  touch "done"
+  echo "$pmf_step is done"
+  cd $main_dir
+fi
 
 # Step 3 - Run simulations
 update_stepnames 2
@@ -196,10 +189,8 @@ if [ -f $this_dir/done ]; then
 else
   mkdir -p $this_dir || die "mkdir -p $this_dir failed"
   cd $this_dir || die "cd $this_dir failed"
-
   cp_from_main_dir $filelist
-  cp_from_main_dir grompp.mdp.template
-  cp_from_last_step conf_start*.gro 
+  cp_from_last_step 'conf.start*.gro' 
 
   do_external simulate pmf
 
