csg_call is now installed, removed some stuff in csg_inverse

diff --git a/scripts/csg_call b/scripts/csg_call
--- a/scripts/csg_call
+++ b/scripts/csg_call
@@ -1,9 +1,8 @@
-#! /bin/bash
+#!/bin/bash
 
 #if not defined try to parse agrument
 if [ -z "${CSGSHARE}" ]; then
    echo Error: Environment values CSGSHARE not defined 1>&2
-   echo Try ${0##*/} --help for help 1>&2
    exit 1
 fi
 
@@ -16,3 +15,14 @@ else
    echo ${0##*/}: Could not run ${CSGSHARE}/scripts/inverse/inverse.sh $@
    exit 1
 fi
+
+export CSGINVERSE=$CSGSHARE/scripts/inverse
+export SOURCE_WRAPPER=$CSGINVERSE/source_wrapper.pl
+export CSGLOG=log.tmp
+source $($SOURCE_WRAPPER functions common) || die "$SOURCE_WRAPPER functions common failed" 
+
+script=$($SOURCE_WRAPPER $1 $2)
+
+echo running $script
+
+do_external $@
