CI: started reworking make_release.sh

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -45,12 +45,12 @@ jobs:
               echo "You cannot deploy a release without explicitly setting the tag" >&2
               exit 1
             fi
-            if [[ ${branch} != stable ]]; then
-              echo "You cannot deploy from a branch that is not 'stable'" >&2
+            if [[ ${branch} != master ]]; then
+              echo "You cannot deploy from a branch that is not 'master'" >&2
               exit 1
             fi
             if [[ ${version} = *-dev ]]; then
-              echo "You cannot deploy from a dev tag" >&2
+              echo "You cannot deploy a dev tag" >&2
               exit 1
             fi
             if [[ -n "${{ github.event.inputs.cmake_args }}" ]]; then
